apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::334111982738:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-G9HL8U6VQOOU
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::334111982738:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-03-09T18:41:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1859"
  uid: 4ea86e2f-9f87-4d52-bca3-dbf536f6f2f3
